name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.75.0
    - name: Check
      run: cargo clippy --no-deps
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
